// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3sLGOs_lGlDOU3RoWAYMAKDG01-y-vyQ',
    appId: '1:1063325978509:web:895f43c1b6a6f2563837c4',
    messagingSenderId: '1063325978509',
    projectId: 'planeapp-43059',
    authDomain: 'planeapp-43059.firebaseapp.com',
    databaseURL: 'https://planeapp-43059-default-rtdb.firebaseio.com',
    storageBucket: 'planeapp-43059.appspot.com',
    measurementId: 'G-3T4WCMXQXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyTIOGPfUkb0Oh2rE62dOYwEVd2Dgl70',
    appId: '1:1063325978509:android:f7684136eb6efdca3837c4',
    messagingSenderId: '1063325978509',
    projectId: 'planeapp-43059',
    databaseURL: 'https://planeapp-43059-default-rtdb.firebaseio.com',
    storageBucket: 'planeapp-43059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA19UJ6pys8snYHjKj1yqyNeF0gsRsEWAs',
    appId: '1:1063325978509:ios:46592494d2b1e2a63837c4',
    messagingSenderId: '1063325978509',
    projectId: 'planeapp-43059',
    databaseURL: 'https://planeapp-43059-default-rtdb.firebaseio.com',
    storageBucket: 'planeapp-43059.appspot.com',
    iosClientId: '1063325978509-3tgp0jjveet5k6nhjr68qiu3emu29j54.apps.googleusercontent.com',
    iosBundleId: 'com.example.planeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA19UJ6pys8snYHjKj1yqyNeF0gsRsEWAs',
    appId: '1:1063325978509:ios:46592494d2b1e2a63837c4',
    messagingSenderId: '1063325978509',
    projectId: 'planeapp-43059',
    databaseURL: 'https://planeapp-43059-default-rtdb.firebaseio.com',
    storageBucket: 'planeapp-43059.appspot.com',
    iosClientId: '1063325978509-3tgp0jjveet5k6nhjr68qiu3emu29j54.apps.googleusercontent.com',
    iosBundleId: 'com.example.planeApp',
  );
}
